repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: check-builtin-literals
    - id: check-yaml
      args: [--unsafe]
    - id: check-json
    - id: check-docstring-first
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: requirements-txt-fixer
    - id: debug-statements
    - id: check-toml
    - id: pretty-format-json
      args: [--autofix]
      language_version: python3.9
    - id: end-of-file-fixer
    - id: flake8
      language_version: python3.9
    - id: forbid-new-submodules
    - id: mixed-line-ending

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    - id: mypy
      name: Mypy typing checks

-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    - id: black
      language_version: python3.9

-   repo: local
    hooks:
    - id: tests
      name: run tests
      entry: pytest
      pass_filenames: false
      language_version: python3.9
      language: system
